#!/bin/sh

# npm test

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Prettify all selected files
echo "$FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write

echo -e "\nValidating Javascript with eslint:"

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep "\.jsx\?$\|\.tsx\?$\|\.js$\|\.ts$")
echo "$STAGED_FILES" | xargs ./node_modules/.bin/eslint --fix

echo -e "Javascript validation completed."

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add
echo "$STAGED_FILES" | xargs git add





# Get the list of staged files in the last commit
files=$(git diff --cached --name-only)

# Regular expression to match desired file types
regex="\.(jsx?|tsx?|js|ts)$"

# Check if any staged files match the regex
if [[ "$files" =~ $regex ]]; then
    echo "Files with specified extensions were changed in the last commit."
    exit 0
else
    echo "No files with specified extensions were changed in the last commit."
    exit 1
fi
exit $?