#!/bin/sh

# npm test

# Supported file types
file_types=".jsx?$|.tsx?$|.js$|.ts$"

# Get staged files with supported types
FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep "$file_types")
[ -z "$FILES" ] && exit 0

# Prettify all selected files
echo "$FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write

echo -e "\nValidating Javascript and Typescript with eslint:"

# Run eslint with fix on staged JS and TS files
echo "$FILES" | xargs ./node_modules/.bin/eslint --fix

# Check for TypeScript compilation errors (adjust the command as needed)
tsc --noEmit --pretty --skipLibCheck --project tsconfig.json "$FILES"

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit $?
